[phases.setup]
nixPkgs = ['nodejs-18_x', 'nodejs-18_x', 'npm-8_x']  # 明確指定版本

[phases.install]
cmds = ['npm install']

[phases.build]
cmds = ['npm run build']

[start]
cmd = 'npm run preview -- --host 0.0.0.0 --port $PORT'